name: Development Branch

on:
  push:
    branches: [ devel ]
    paths-ignore:
    - '*/README.md'
    - '*/LICENSE'
    - '*/.gitignore'
    - '.github/ISSUE_TEMPLATE/*'
    - 'src/deprecated/*'

jobs:
   test-devel-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout devel branch
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.10
    - name: Install Flake8, pytest & throne (from source)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create throne directory & config file
      run: |
        mkdir $HOME/.throne
        touch $HOME/.throne/config.yml
    - name: Test with pytest
      env:
        SHODAN_KEY: ${{ secrets.SHODAN_KEY }}
        THRONE_USER: ${{ secrets.THRONE_USER }}
        THRONE_PASS: ${{ secrets.THRONE_PASS }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        # pytest -s -vvvv tests/create_config.py && pytest -s -vvvv
        # pytest --cov=./
        python tests/create_config.py
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true