name: Master Branch

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '*/README.md'
    - '*/LICENSE'
    - '*/.gitignore'
    - '.github/ISSUE_TEMPLATE/*'
    - 'src/deprecated/*'

jobs:
   test-master-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Flake8, pytest & throne (from source)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        SHODAN_KEY: ${{ secrets.SHODAN_KEY }}
        THRONE_USER: ${{ secrets.THRONE_USER }}
        THRONE_PASS: ${{ secrets.THRONE_PASS }}
      run: |
        pytest -s -v tests/create_config.py && pytest -s -v